export function random(n: number): string[] {
  let choices = examples();
  let result: any[] = [];
  for (let i = 0; i < n; i++) {
    result.push(choices.splice(Math.floor(Math.random() * choices.length), 1)[0]);
  }

  return result;
}

function examples(): string[] {
  return [
    "new tab",
    "next tab",
    "previous tab",
    "close tab",
    "go to tab three",
    "next word",
    "next line",
    "previous line",
    "split left",
    "split right",
    "left window",
    "right window",
    "line one",
    "copy next two words",
    "go to hello world",
    "paste",
    "cut function",
    "copy class",
    "delete if",
    "indent line two times",
    "indent next five lines",
    "dedent line",
    "save",
    "style file",
    "undo",
    "redo",
    "copy request manager",
    "change return value to 50",
    "change fly to jump",
    "newline",
    "next character",
    "previous word",
    "go to end of line",
    "go to start of word",
    "delete to end of line",
    "delete three words",
    "go to second word",
    "delete second argument",
    "copy previous five lines",
    "delete last four words",
    "next class",
    "previous function",
    "go to return value",
    "cut third import",
    "insert equals three",
    "insert value equals string hello",
    "insert all caps my value",
    "insert a equals b plus one",
    "insert times sum of n",
    "add argument bar",
    "add function hello",
    "add parameter foo",
    "add class styler",
    "add import requests",
    "add import numpy as np",
    "add assert false",
    "add decorator app dot get",
    "add return true",
    "add if a less than three",
    "add method init",
    "add return",
    "add while counter greater than zero",
    "add try",
    "add print hi",
    "add function underscore get",
    "add parent exception",
  ];
}
