package corpusgen.util;

import java.util.Arrays;
import java.util.List;
import javax.inject.Inject;
import javax.inject.Singleton;

@Singleton
public class Apps {
  @Inject
  public Apps() {}

  public List<String> common = Arrays.asList(
    "one password",
    "adobe",
    "airmail",
    "android studio",
    "atom",
    "auto hotkey",
    "bit torrent",
    "calculator",
    "calendar",
    "chrome",
    "code",
    "dictionary",
    "docker",
    "dragon",
    "dream weaver",
    "drive",
    "dropbox",
    "excel",
    "exchange",
    "explorer",
    "evernote",
    "face time",
    "final cut pro",
    "finder",
    "firefox",
    "flash",
    "gimp",
    "git",
    "gmail",
    "gnome",
    "google",
    "google drive",
    "gvim",
    "internet explorer",
    "intellij",
    "i photo",
    "i message",
    "i term",
    "i tunes",
    "irc",
    "jet brains",
    "kde",
    "libre office",
    "light room",
    "mail",
    "net beans",
    "note pad",
    "notes",
    "office",
    "one drive",
    "one note",
    "opera",
    "outlook",
    "photos",
    "photo shop",
    "php my admin",
    "power point",
    "preview",
    "py charm",
    "safari",
    "slack",
    "smart git",
    "shell",
    "skype",
    "spotify",
    "sublime",
    "system",
    "sql server",
    "steam",
    "terminal",
    "term",
    "tmux",
    "thunderbird",
    "text edit",
    "r studio",
    "reminders",
    "u torrent",
    "virtual desktop",
    "virtual box",
    "visual studio",
    "visio",
    "vlc",
    "vm ware",
    "vnc",
    "vpn",
    "vs code",
    "windows server",
    "web storm",
    "quick time",
    "xcode",
    "xorg",
    "xterm"
  );
}
